# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mydb
  pool: 5
  username: root
  password: asdfgh

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mydb
  pool: 5
  username: root
  password: asdfgh
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mydb_testing
  pool: 5
  username: root
  password: asdfgh
  socket: /var/run/mysqld/mysqld.sock